laberinto/lab_corredor/urls.py
from django.conf.urls import url
from django.urls import path
from .views import LaberintoCorredor

app_name="corredor"

urlpatterns = [
    path("lab_corredor", LaberintoCorredor.as_view(), name="corredor")
]

laberinto/lab_icaro/urls.py
from django.conf.urls import url
from django.urls import path
from .views import LaberintoIcaro

app_name = "icaro"


urlpatterns = [
    path("lab_icaro", LaberintoIcaro.as_view(), name="icaro")
]

laberinto/laberinto/urls.py
"""URLS GENERAL"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("leyenda/",
         include ("leyenda.urls", namespace="leyenda"),
         name="leyenda"),
    # view de laberinto de icaro
    path("lab_icaro/",
         include("lab_icaro.urls", namespace="lab_icaro"),
         name="icaro"),
    # view del corredor del laberinto
    path("lab_corredor/",
         include("lab_corredor.urls", namespace="lab_corredor"),
         name="corredor"),
    #view de pacman
    path("pac_man/",
        include("pac_man.urls", namespace="pac_man"),
        name="pacman"),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)

laberinto/leyenda/urls.py
"""  """
from django.conf.urls import url
from django.urls import path
from .views import IndiceLeyendasView, LeyendaView




app_name =  "leyenda"

urlpatterns = [
    path("indice", IndiceLeyendasView.as_view(), name="indice"),
    path("nombre=<slug:nombre>/", LeyendaView.as_view(), name="nombre"),
]

laberinto/pac_man/urls.py
from django.conf.urls import url
from django.urls import path
from .views import PacMan

app_name = "pacman"


urlpatterns = [
    path("pac_man", PacMan.as_view(), name="pacman")
]

laberinto/lab_corredor/models.py
from django.db import models

# Create your models here.

laberinto/lab_icaro/models.py
from django.db import models

# Create your models here.

laberinto/leyenda/models.py
from django.db import models

# Create your models here.

laberinto/pac_man/models.py
from django.db import models

# Create your models here.

laberinto/lab_corredor/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
class LaberintoCorredor(TemplateView):
    template_name = "lab_corredor/index.dj.html"

laberinto/lab_icaro/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
class LaberintoIcaro(TemplateView):
    template_name = "lab_icaro/index.dj.html"

laberinto/leyenda/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .textos import diccionario
from pprint import pprint

# Create your views here.

class IndiceLeyendasView(TemplateView):
    template_name = "leyenda/index.dj.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"leyendas":diccionario})
        return context


class LeyendaView(TemplateView):
    template_name = "leyenda/texto.dj.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        nombre = context.get('nombre')
        leyenda = diccionario.get(nombre,{})
        if not leyenda:
            leyenda = {"texto":f"No existe leyenda {nombre}"}
        pprint(leyenda)
        context.update(leyenda)
        return context

laberinto/pac_man/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
class PacMan(TemplateView):
    template_name = "pac_man/index.dj.html"

laberinto/lab_corredor/templates/lab_corredor/index.dj.html
{% extends "base.dj.html" %}

{% block encabezado %}
<h1>Laberinto del Corredor - Maze runner</h1>
{% endblock encabezado %}


{% block contenido %}

<section>
	<a href="{% url 'leyenda:indice' %}">Indice</a>
</section>
<p>
Al despertar dentro de una oscura caja en movimiento, Thomas solo recuerda su nombre. No sabe quién es. Tampoco hacia dónde va. Pero no está solo: cuando el ascensor llega a su destino, las puertas se abren y se ve rodeado por un grupo de jóvenes (todos varones).

El Glade (el Claro en España, el Área en Hispanoamérica) es un espacio abierto cercado por muros gigantescos llenos de vegetación. Al igual que Thomas, ninguno de ellos sabe cómo ha llegado allí. Ni por qué. De lo que están seguros es de que cada mañana las puertas de piedra que los separan del laberinto que los rodea se abren y por la noche, se cierran. Y que cada mes alguien nuevo es entregado por el ascensor.

Un hecho altera de forma radical la rutina del lugar: días después de la llegada de Thomas llega una chica, la primera enviada al Glade, y más sorprendente todavía es el mensaje que trae. Thomas será más importante de lo que imagina. Pero para eso deberá descubrir los sombríos secretos guardados en su mente. Por alguna razón, sabe que para lograrlo debe correr. Correr será la clave, o morirá.
</p>
{% endblock contenido %}

laberinto/lab_icaro/templates/lab_icaro/index.dj.html
{% extends "base.dj.html" %}

{% block encabezado %}
<h1>Laberinto de Ícaro</h1>


{% endblock encabezado %}


{% block contenido %}

<section>
	<a href="{% url 'leyenda:indice' %}">Indice</a>
</section>
<p>
El Laberinto de Creta es, en la mitología griega, el laberinto construido por Dédalo para esconder al Minotauro. 
En la actualidad, se piensa que la leyenda del laberinto tiene su base en el palacio de Cnosos. Una construcción tan sofisticada y de alta tecnología como dicho palacio, repleto de múltiples habitaciones y con todas las mejoras conocidas por la tecnología de entonces (incluyendo un sistema de alcantarillado) que debió haber parecido a los aqueos algo intrincado. Apoya esta tesis el hecho de que en el palacio de Cnosos se han encontrado dibujos de hachas de doble filo por doquier, que en griego se llaman labrys, y que habrían dado nombre a la construcción.
</p>
{% endblock contenido %}

laberinto/leyenda/templates/leyenda/base_app.dj.html
{% extends "base.dj.html" %}
{% load static %}

{% block extra_css %}
<link 
	rel="stylesheet" 
	href="{% static 'leyenda/css/estilos.css' %}">
{%endblock%}

laberinto/leyenda/templates/leyenda/index.dj.html
{% extends "leyenda/base_app.dj.html"  %}
{% block encabezado  %}
<h1>Índice de leyendas sobre laberintos</h1>
{% endblock encabezado  %}

{% block contenido %}

<!-- <ul>
    <li>Laberinto de Ícaro - <a href="{% url 'leyenda:nombre' 'icaro' %}">Ver</a></li>
    <li>El corredor del laberinto - <a href="{% url 'leyenda:nombre' 'corredor' %}">Ver</a></li>
    <li>Pac-man - <a href="{% url 'leyenda:nombre' 'pacman' %}">Ver</a></li> 
    <li>Resumen</li>
</ul> -->
    
        <ul id="indice_leyendas">
            {% for nombre, data in leyendas.items %}
            <li>
                {% include 'leyenda/item_link.dj.html' %}
            </li>
            {% endfor %}
        </ul>
{% endblock contenido  %}

laberinto/leyenda/templates/leyenda/item_link.dj.html
{% load static %}

<div 
  id="item-link"  
  class="pure-g"
>
  <!-- imagen del contenido -->
  <div 
    id="imagen-item-link"  
    class="pure-u-8-24"
  >
    <figure>
      <img 
        class="pure-img"
        src="{% static 'leyenda/img/' %}{{data.imagen}}"
      >
    </figure>
  </div>
  <!-- contenido texto -->
  <div 
    id="contenido-item-link"
    class="pure-u-16-24"
  >
    <h4>{{data.titulo}}</h4>
    <section>
      <p>{{data.resumen}}</p>
    </section>
      <a
         href="{% url 'leyenda:nombre' nombre %}"
      >
        Ver
     </a>
  </div>
</div>

laberinto/leyenda/templates/leyenda/texto.dj.html
{% extends "base.dj.html" %}

{% block encabezado %}
<h1>{{titulo}}</h1>


{% endblock encabezado %}


{% block contenido %}

<section>
	<a href="{% url 'leyenda:indice' %}">Indice</a>
</section>
{{texto|safe}}
{% endblock contenido %}

laberinto/pac_man/templates/pac_man/index.dj.html
{% extends "base.dj.html" %}

{% block encabezado %}
<h1>Pac-man</h1>


{% endblock encabezado %}


{% block contenido %}

<section>
	<a href="{% url 'leyenda:indice' %}">Indice</a>
</section>
<p>Los <b>laberintos</b> son los niveles de <i><a href="/es/wiki/Pac-Man_(videojuego)" title="Pac-Man (videojuego)">Pac-Man</a></i>. En el centro del laberinto siempre hay una <a href="/es/wiki/Casa" title="Casa">casa</a> por donde los <a href="/es/wiki/Fantasmas" title="Fantasmas">fantasmas</a> se generan y regeneran.
</p><p>Todos los niveles, tienen el mismo laberinto con el mismo color y forma. En el nivel 256 no se puede pasar debido al <a href="/es/wiki/Glitch_del_laberinto_256" title="Glitch del laberinto 256">glitch del laberinto 256</a>, donde la pantalla se divide, haciendo que este sea el nivel final.
</p>

{% endblock contenido %}

laberinto/templates/base.dj.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{titulo}}</title>
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1">
        {% include "estilos.dj.html" %}
        {% block extra_css %}
        {% endblock %}
    </head>
    <body id="cuerpo">
        <div id="encabezado" class="">
        {% block encabezado %}
        {% endblock encabezado %}
        </div>
        <article
            id="contenido"
            class="">
            <div class="">
            {% block menu %}
            {% endblock menu %}
            </div>
            <div class="">
            {% block contenido %}
            {% endblock contenido %}
            </div>
        </article>
    </body>
</html>

laberinto/templates/estilos.dj.html
<link
    rel="stylesheet"
    href="https://unpkg.com/purecss@2.0.6/build/pure-min.css"
    integrity="sha384-Uu6IeWbM+gzNVXJcM9XV3SohHtmWE+3VGi496jvgX1jyvDTXfdK+rfZc8C1Aehk5"
    crossorigin="anonymous">
<link
    rel="stylesheet"
    href="https://unpkg.com/purecss@2.0.6/build/grids-responsive-min.css">